# Generated by Django 4.1.5 on 2023-06-21 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_category_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='boot_title',
            new_name='book_title',
        ),
    ]
